apiVersion: v2
name: sacunxt
description: A Helm chart for SacuNXT Connector Framework - Complete microservices deployment
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - sacunxt
  - connector
  - microservices
  - kafka
  - postgresql
  - redis
home: https://sacumen.com
sources:
  - https://github.com/sacumen/sacunxt
maintainers:
  - name: Sacumen Team
    email: suthan.natarajan@sacumen.com
icon: https://sacumen.com/media/images/Sacumen-Logo-500px.png
annotations:
  category: Application
  licenses: Apache-2.0
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: kafka
    version: "22.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
